language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - 'CTX=default:whatever'
    - 'CTX=c_extension_support:yes,c_extension_optional:yes'
    - 'CTX=c_extension_support:yes,c_extension_optional:no'
    - 'CTX=tests_use_pytest:no'
    - 'CTX=tests_use_pytest:no,c_extension_support:yes,c_extension_optional:yes'
    - 'CTX=tests_use_pytest:no,c_extension_support:yes,c_extension_optional:no'
    - 'CTX=tests_configurator:no'
    - 'CTX=tests_configurator:no,c_extension_support:yes,c_extension_optional:yes'
    - 'CTX=tests_configurator:no,c_extension_support:yes,c_extension_optional:no'
    - 'CTX=tests_configurator:no,tests_use_pytest:no'
    - 'CTX=tests_configurator:no,tests_use_pytest:no,c_extension_support:yes,c_extension_optional:yes'
    - 'CTX=tests_configurator:no,tests_use_pytest:no,c_extension_support:yes,c_extension_optional:no'

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -I -U tox cookiecutter
script:
  - 'echo "{default_context: {$(echo $CTX | sed s/\\b/\"/g)}}" > ~/.cookiecutterrc'
  - cat ~/.cookiecutterrc
  - cookiecutter --no-input .
  - cd python-nameless
  - tox
notifications:
  email:
    on_success: never
    on_failure: always

