language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix-nose
    - ENV=matrix-nose-cext
    - ENV=matrix-nose-cext-optional
    - ENV=matrix-nose-fnaccents
    - ENV=matrix-nose-fndoublequote
    - ENV=matrix-nose-fnquote
    - ENV=matrix-nose-fntriplequote
    - ENV=matrix-nose-pnaccents
    - ENV=matrix-nose-pndoublequote
    - ENV=matrix-nose-pnquote
    - ENV=matrix-nose-pntriplequote
    - ENV=matrix-pytest
    - ENV=matrix-pytest-cext
    - ENV=matrix-pytest-cext-optional
    - ENV=matrix-pytest-fnaccents
    - ENV=matrix-pytest-fndoublequote
    - ENV=matrix-pytest-fnquote
    - ENV=matrix-pytest-fntriplequote
    - ENV=matrix-pytest-pnaccents
    - ENV=matrix-pytest-pndoublequote
    - ENV=matrix-pytest-pnquote
    - ENV=matrix-pytest-pntriplequote
    - ENV=plain-nose
    - ENV=plain-nose-cext
    - ENV=plain-nose-cext-optional
    - ENV=plain-nose-fnaccents
    - ENV=plain-nose-fndoublequote
    - ENV=plain-nose-fnquote
    - ENV=plain-nose-fntriplequote
    - ENV=plain-nose-pnaccents
    - ENV=plain-nose-pndoublequote
    - ENV=plain-nose-pnquote
    - ENV=plain-nose-pntriplequote
    - ENV=plain-pytest
    - ENV=plain-pytest-cext
    - ENV=plain-pytest-cext-optional
    - ENV=plain-pytest-fnaccents
    - ENV=plain-pytest-fndoublequote
    - ENV=plain-pytest-fnquote
    - ENV=plain-pytest-fntriplequote
    - ENV=plain-pytest-pnaccents
    - ENV=plain-pytest-pndoublequote
    - ENV=plain-pytest-pnquote
    - ENV=plain-pytest-pntriplequote
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
