language: python
python:
  - 2.7
  - 3.4
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix-nose-cext-fndef-pndef
    - ENV=matrix-nose-cext-optional-fndef-pndef
    - ENV=matrix-nose-fnaccents-pndef
    - ENV=matrix-nose-fndef-pnaccents
    - ENV=matrix-nose-fndef-pndef
    - ENV=matrix-nose-fndef-pndoublequote
    - ENV=matrix-nose-fndef-pnquote
    - ENV=matrix-nose-fndef-pntriplequote
    - ENV=matrix-nose-fndoublequote-pndef
    - ENV=matrix-nose-fnquote-pndef
    - ENV=matrix-nose-fntriplequote-pndef
    - ENV=matrix-pytest-cext-fndef-pndef
    - ENV=matrix-pytest-cext-optional-fndef-pndef
    - ENV=matrix-pytest-fnaccents-pndef
    - ENV=matrix-pytest-fndef-pnaccents
    - ENV=matrix-pytest-fndef-pndef
    - ENV=matrix-pytest-fndef-pndoublequote
    - ENV=matrix-pytest-fndef-pnquote
    - ENV=matrix-pytest-fndef-pntriplequote
    - ENV=matrix-pytest-fndoublequote-pndef
    - ENV=matrix-pytest-fnquote-pndef
    - ENV=matrix-pytest-fntriplequote-pndef
    - ENV=plain-nose-cext-fndef-pndef
    - ENV=plain-nose-cext-optional-fndef-pndef
    - ENV=plain-nose-fnaccents-pndef
    - ENV=plain-nose-fndef-pnaccents
    - ENV=plain-nose-fndef-pndef
    - ENV=plain-nose-fndef-pndoublequote
    - ENV=plain-nose-fndef-pnquote
    - ENV=plain-nose-fndef-pntriplequote
    - ENV=plain-nose-fndoublequote-pndef
    - ENV=plain-nose-fnquote-pndef
    - ENV=plain-nose-fntriplequote-pndef
    - ENV=plain-pytest-cext-fndef-pndef
    - ENV=plain-pytest-cext-optional-fndef-pndef
    - ENV=plain-pytest-fnaccents-pndef
    - ENV=plain-pytest-fndef-pnaccents
    - ENV=plain-pytest-fndef-pndef
    - ENV=plain-pytest-fndef-pndoublequote
    - ENV=plain-pytest-fndef-pnquote
    - ENV=plain-pytest-fndef-pntriplequote
    - ENV=plain-pytest-fndoublequote-pndef
    - ENV=plain-pytest-fnquote-pndef
    - ENV=plain-pytest-fntriplequote-pndef
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
