language: python
python:
  - 3.5
sudo: false
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix-nose-argparse-py3doc
    - ENV=matrix-nose-cext-argparse-py3doc
    - ENV=matrix-nose-cext-click-py3doc
    - ENV=matrix-nose-cext-cython-nocli-py3doc
    - ENV=matrix-nose-cext-cython-nocli-rtd
    - ENV=matrix-nose-cext-nocli-py3doc
    - ENV=matrix-nose-cext-nocli-rtd
    - ENV=matrix-nose-cext-optional-cython-nocli-py3doc
    - ENV=matrix-nose-cext-optional-cython-nocli-rtd
    - ENV=matrix-nose-cext-optional-nocli-py3doc
    - ENV=matrix-nose-cext-optional-nocli-rtd
    - ENV=matrix-nose-cext-plain-py3doc
    - ENV=matrix-nose-click-py3doc
    - ENV=matrix-nose-nocli-py3doc
    - ENV=matrix-nose-nocli-rtd
    - ENV=matrix-nose-plain-py3doc
    - ENV=matrix-pytest-argparse-py3doc
    - ENV=matrix-pytest-cext-argparse-py3doc
    - ENV=matrix-pytest-cext-click-py3doc
    - ENV=matrix-pytest-cext-cython-nocli-py3doc
    - ENV=matrix-pytest-cext-cython-nocli-rtd
    - ENV=matrix-pytest-cext-nocli-py3doc
    - ENV=matrix-pytest-cext-nocli-rtd
    - ENV=matrix-pytest-cext-optional-cython-nocli-py3doc
    - ENV=matrix-pytest-cext-optional-cython-nocli-rtd
    - ENV=matrix-pytest-cext-optional-nocli-py3doc
    - ENV=matrix-pytest-cext-optional-nocli-rtd
    - ENV=matrix-pytest-cext-plain-py3doc
    - ENV=matrix-pytest-click-py3doc
    - ENV=matrix-pytest-nocli-py3doc
    - ENV=matrix-pytest-nocli-rtd
    - ENV=matrix-pytest-plain-py3doc
    - ENV=matrix-separatecover-nose-argparse-py3doc
    - ENV=matrix-separatecover-nose-cext-argparse-py3doc
    - ENV=matrix-separatecover-nose-cext-click-py3doc
    - ENV=matrix-separatecover-nose-cext-cython-nocli-py3doc
    - ENV=matrix-separatecover-nose-cext-cython-nocli-rtd
    - ENV=matrix-separatecover-nose-cext-nocli-py3doc
    - ENV=matrix-separatecover-nose-cext-nocli-rtd
    - ENV=matrix-separatecover-nose-cext-optional-cython-nocli-py3doc
    - ENV=matrix-separatecover-nose-cext-optional-cython-nocli-rtd
    - ENV=matrix-separatecover-nose-cext-optional-nocli-py3doc
    - ENV=matrix-separatecover-nose-cext-optional-nocli-rtd
    - ENV=matrix-separatecover-nose-cext-plain-py3doc
    - ENV=matrix-separatecover-nose-click-py3doc
    - ENV=matrix-separatecover-nose-nocli-py3doc
    - ENV=matrix-separatecover-nose-nocli-rtd
    - ENV=matrix-separatecover-nose-plain-py3doc
    - ENV=matrix-separatecover-pytest-argparse-py3doc
    - ENV=matrix-separatecover-pytest-cext-argparse-py3doc
    - ENV=matrix-separatecover-pytest-cext-click-py3doc
    - ENV=matrix-separatecover-pytest-cext-cython-nocli-py3doc
    - ENV=matrix-separatecover-pytest-cext-cython-nocli-rtd
    - ENV=matrix-separatecover-pytest-cext-nocli-py3doc
    - ENV=matrix-separatecover-pytest-cext-nocli-rtd
    - ENV=matrix-separatecover-pytest-cext-optional-cython-nocli-py3doc
    - ENV=matrix-separatecover-pytest-cext-optional-cython-nocli-rtd
    - ENV=matrix-separatecover-pytest-cext-optional-nocli-py3doc
    - ENV=matrix-separatecover-pytest-cext-optional-nocli-rtd
    - ENV=matrix-separatecover-pytest-cext-plain-py3doc
    - ENV=matrix-separatecover-pytest-click-py3doc
    - ENV=matrix-separatecover-pytest-nocli-py3doc
    - ENV=matrix-separatecover-pytest-nocli-rtd
    - ENV=matrix-separatecover-pytest-plain-py3doc
    - ENV=plain-nose-argparse-py3doc
    - ENV=plain-nose-cext-argparse-py3doc
    - ENV=plain-nose-cext-click-py3doc
    - ENV=plain-nose-cext-cython-nocli-py3doc
    - ENV=plain-nose-cext-cython-nocli-rtd
    - ENV=plain-nose-cext-nocli-py3doc
    - ENV=plain-nose-cext-nocli-rtd
    - ENV=plain-nose-cext-optional-cython-nocli-py3doc
    - ENV=plain-nose-cext-optional-cython-nocli-rtd
    - ENV=plain-nose-cext-optional-nocli-py3doc
    - ENV=plain-nose-cext-optional-nocli-rtd
    - ENV=plain-nose-cext-plain-py3doc
    - ENV=plain-nose-click-py3doc
    - ENV=plain-nose-nocli-py3doc
    - ENV=plain-nose-nocli-rtd
    - ENV=plain-nose-plain-py3doc
    - ENV=plain-pytest-argparse-py3doc
    - ENV=plain-pytest-cext-argparse-py3doc
    - ENV=plain-pytest-cext-click-py3doc
    - ENV=plain-pytest-cext-cython-nocli-py3doc
    - ENV=plain-pytest-cext-cython-nocli-rtd
    - ENV=plain-pytest-cext-nocli-py3doc
    - ENV=plain-pytest-cext-nocli-rtd
    - ENV=plain-pytest-cext-optional-cython-nocli-py3doc
    - ENV=plain-pytest-cext-optional-cython-nocli-rtd
    - ENV=plain-pytest-cext-optional-nocli-py3doc
    - ENV=plain-pytest-cext-optional-nocli-rtd
    - ENV=plain-pytest-cext-plain-py3doc
    - ENV=plain-pytest-click-py3doc
    - ENV=plain-pytest-nocli-py3doc
    - ENV=plain-pytest-nocli-rtd
    - ENV=plain-pytest-plain-py3doc
    - ENV=plain-separatecover-nose-argparse-py3doc
    - ENV=plain-separatecover-nose-cext-argparse-py3doc
    - ENV=plain-separatecover-nose-cext-click-py3doc
    - ENV=plain-separatecover-nose-cext-cython-nocli-py3doc
    - ENV=plain-separatecover-nose-cext-cython-nocli-rtd
    - ENV=plain-separatecover-nose-cext-nocli-py3doc
    - ENV=plain-separatecover-nose-cext-nocli-rtd
    - ENV=plain-separatecover-nose-cext-optional-cython-nocli-py3doc
    - ENV=plain-separatecover-nose-cext-optional-cython-nocli-rtd
    - ENV=plain-separatecover-nose-cext-optional-nocli-py3doc
    - ENV=plain-separatecover-nose-cext-optional-nocli-rtd
    - ENV=plain-separatecover-nose-cext-plain-py3doc
    - ENV=plain-separatecover-nose-click-py3doc
    - ENV=plain-separatecover-nose-nocli-py3doc
    - ENV=plain-separatecover-nose-nocli-rtd
    - ENV=plain-separatecover-nose-plain-py3doc
    - ENV=plain-separatecover-pytest-argparse-py3doc
    - ENV=plain-separatecover-pytest-cext-argparse-py3doc
    - ENV=plain-separatecover-pytest-cext-click-py3doc
    - ENV=plain-separatecover-pytest-cext-cython-nocli-py3doc
    - ENV=plain-separatecover-pytest-cext-cython-nocli-rtd
    - ENV=plain-separatecover-pytest-cext-nocli-py3doc
    - ENV=plain-separatecover-pytest-cext-nocli-rtd
    - ENV=plain-separatecover-pytest-cext-optional-cython-nocli-py3doc
    - ENV=plain-separatecover-pytest-cext-optional-cython-nocli-rtd
    - ENV=plain-separatecover-pytest-cext-optional-nocli-py3doc
    - ENV=plain-separatecover-pytest-cext-optional-nocli-rtd
    - ENV=plain-separatecover-pytest-cext-plain-py3doc
    - ENV=plain-separatecover-pytest-click-py3doc
    - ENV=plain-separatecover-pytest-nocli-py3doc
    - ENV=plain-separatecover-pytest-nocli-rtd
    - ENV=plain-separatecover-pytest-plain-py3doc
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools
  - pip wheel tox virtualenv cookiecutter bumpversion
  - pip wheel pytest-capturelog pytest-cov pytest
  - pip wheel nose coverage
  - pip wheel cpp-coveralls
  - pip wheel jinja2 matrix
  - pip wheel docutils check-manifest flake8 readme-renderer pygments
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
