language: python
dist: trusty
python: 3.6
group: deprecated-2017Q2
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=mconf-sepcov-nose-pure-argpa-pet-flake8-plain-gith
    - ENV=mconf-sepcov-nose-pure-click-pet-flake8-plain-gith
    - ENV=mconf-sepcov-nose-pure-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-nose-pure-plain-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-pure-click-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV=mconf-sepcov-pyte-pure-plain-pet-flake8-plain-gith
    - ENV=mconf-single-nose-pure-argpa-pet-flake8-plain-gith
    - ENV=mconf-single-nose-pure-click-pet-flake8-plain-gith
    - ENV=mconf-single-nose-pure-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-nose-pure-plain-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-pure-click-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV=mconf-single-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV=mconf-single-pyte-pure-plain-pet-flake8-plain-gith
    - ENV=plain-sepcov-nose-pure-argpa-pet-flake8-plain-gith
    - ENV=plain-sepcov-nose-pure-click-pet-flake8-plain-gith
    - ENV=plain-sepcov-nose-pure-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-nose-pure-plain-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-pure-click-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV=plain-sepcov-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV=plain-sepcov-pyte-pure-plain-pet-flake8-plain-gith
    - ENV=plain-single-nose-pure-argpa-pet-flake8-plain-gith
    - ENV=plain-single-nose-pure-click-pet-flake8-plain-gith
    - ENV=plain-single-nose-pure-nocli-pet-flake8-plain-gith
    - ENV=plain-single-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-nose-pure-plain-pet-flake8-plain-gith
    - ENV=plain-single-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV=plain-single-pyte-cext-nocli-pet-flake8-plain-priv
    - ENV=plain-single-pyte-cext-nocli-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-cext-nocli-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-cext-nocli-pet-pylama-plain-gith
    - ENV=plain-single-pyte-cext-nocli-pet-pylama-plain-priv
    - ENV=plain-single-pyte-cext-nocli-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-cext-nocli-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-pyte-cext-nocli-rtd-flake8-plain-priv
    - ENV=plain-single-pyte-cext-nocli-rtd-flake8-stprq-gith
    - ENV=plain-single-pyte-cext-nocli-rtd-flake8-stprq-priv
    - ENV=plain-single-pyte-cext-nocli-rtd-pylama-plain-gith
    - ENV=plain-single-pyte-cext-nocli-rtd-pylama-plain-priv
    - ENV=plain-single-pyte-cext-nocli-rtd-pylama-stprq-gith
    - ENV=plain-single-pyte-cext-nocli-rtd-pylama-stprq-priv
    - ENV=plain-single-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV=plain-single-pyte-cext-opt-nocli-pet-flake8-plain-priv
    - ENV=plain-single-pyte-cext-opt-nocli-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-cext-opt-nocli-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-cext-opt-nocli-pet-pylama-plain-gith
    - ENV=plain-single-pyte-cext-opt-nocli-pet-pylama-plain-priv
    - ENV=plain-single-pyte-cext-opt-nocli-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-cext-opt-nocli-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-flake8-plain-priv
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-flake8-stprq-gith
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-flake8-stprq-priv
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-pylama-plain-gith
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-pylama-plain-priv
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-pylama-stprq-gith
    - ENV=plain-single-pyte-cext-opt-nocli-rtd-pylama-stprq-priv
    - ENV=plain-single-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV=plain-single-pyte-cffi-nocli-pet-flake8-plain-priv
    - ENV=plain-single-pyte-cffi-nocli-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-cffi-nocli-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-cffi-nocli-pet-pylama-plain-gith
    - ENV=plain-single-pyte-cffi-nocli-pet-pylama-plain-priv
    - ENV=plain-single-pyte-cffi-nocli-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-cffi-nocli-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-pyte-cffi-nocli-rtd-flake8-plain-priv
    - ENV=plain-single-pyte-cffi-nocli-rtd-flake8-stprq-gith
    - ENV=plain-single-pyte-cffi-nocli-rtd-flake8-stprq-priv
    - ENV=plain-single-pyte-cffi-nocli-rtd-pylama-plain-gith
    - ENV=plain-single-pyte-cffi-nocli-rtd-pylama-plain-priv
    - ENV=plain-single-pyte-cffi-nocli-rtd-pylama-stprq-gith
    - ENV=plain-single-pyte-cffi-nocli-rtd-pylama-stprq-priv
    - ENV=plain-single-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV=plain-single-pyte-cyth-nocli-pet-flake8-plain-priv
    - ENV=plain-single-pyte-cyth-nocli-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-cyth-nocli-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-cyth-nocli-pet-pylama-plain-gith
    - ENV=plain-single-pyte-cyth-nocli-pet-pylama-plain-priv
    - ENV=plain-single-pyte-cyth-nocli-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-cyth-nocli-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-pyte-cyth-nocli-rtd-flake8-plain-priv
    - ENV=plain-single-pyte-cyth-nocli-rtd-flake8-stprq-gith
    - ENV=plain-single-pyte-cyth-nocli-rtd-flake8-stprq-priv
    - ENV=plain-single-pyte-cyth-nocli-rtd-pylama-plain-gith
    - ENV=plain-single-pyte-cyth-nocli-rtd-pylama-plain-priv
    - ENV=plain-single-pyte-cyth-nocli-rtd-pylama-stprq-gith
    - ENV=plain-single-pyte-cyth-nocli-rtd-pylama-stprq-priv
    - ENV=plain-single-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV=plain-single-pyte-pure-argpa-pet-flake8-plain-priv
    - ENV=plain-single-pyte-pure-argpa-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-pure-argpa-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-pure-argpa-pet-pylama-plain-gith
    - ENV=plain-single-pyte-pure-argpa-pet-pylama-plain-priv
    - ENV=plain-single-pyte-pure-argpa-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-pure-argpa-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-pure-click-pet-flake8-plain-gith
    - ENV=plain-single-pyte-pure-click-pet-flake8-plain-priv
    - ENV=plain-single-pyte-pure-click-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-pure-click-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-pure-click-pet-pylama-plain-gith
    - ENV=plain-single-pyte-pure-click-pet-pylama-plain-priv
    - ENV=plain-single-pyte-pure-click-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-pure-click-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV=plain-single-pyte-pure-nocli-pet-flake8-plain-priv
    - ENV=plain-single-pyte-pure-nocli-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-pure-nocli-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-pure-nocli-pet-pylama-plain-gith
    - ENV=plain-single-pyte-pure-nocli-pet-pylama-plain-priv
    - ENV=plain-single-pyte-pure-nocli-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-pure-nocli-pet-pylama-stprq-priv
    - ENV=plain-single-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV=plain-single-pyte-pure-nocli-rtd-flake8-plain-priv
    - ENV=plain-single-pyte-pure-nocli-rtd-flake8-stprq-gith
    - ENV=plain-single-pyte-pure-nocli-rtd-flake8-stprq-priv
    - ENV=plain-single-pyte-pure-nocli-rtd-pylama-plain-gith
    - ENV=plain-single-pyte-pure-nocli-rtd-pylama-plain-priv
    - ENV=plain-single-pyte-pure-nocli-rtd-pylama-stprq-gith
    - ENV=plain-single-pyte-pure-nocli-rtd-pylama-stprq-priv
    - ENV=plain-single-pyte-pure-plain-pet-flake8-plain-gith
    - ENV=plain-single-pyte-pure-plain-pet-flake8-plain-priv
    - ENV=plain-single-pyte-pure-plain-pet-flake8-stprq-gith
    - ENV=plain-single-pyte-pure-plain-pet-flake8-stprq-priv
    - ENV=plain-single-pyte-pure-plain-pet-pylama-plain-gith
    - ENV=plain-single-pyte-pure-plain-pet-pylama-plain-priv
    - ENV=plain-single-pyte-pure-plain-pet-pylama-stprq-gith
    - ENV=plain-single-pyte-pure-plain-pet-pylama-stprq-priv
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - git --version
  - ci/test.sh $ENV
  - |
    set -ex
    cd python-nameless
    if [[ -n "$TRAVIS_PULL_REQUEST" ]]; then
      $PR="pr${TRAVIS_PULL_REQUEST}-"
    else
      $PR=""
    fi
    git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV

notifications:
  email:
    on_success: never
    on_failure: always
