language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix
    - ENV=matrix-cext
    - ENV=matrix-cext-optional
    - ENV=matrix-fnaccents
    - ENV=matrix-fndoublequote
    - ENV=matrix-fnquote
    - ENV=matrix-fntriplequote
    - ENV=matrix-pnaccents
    - ENV=matrix-pndoublequote
    - ENV=matrix-pnquote
    - ENV=matrix-pntriplequote
    - ENV=plain
    - ENV=plain-cext
    - ENV=plain-cext-optional
    - ENV=plain-fnaccents
    - ENV=plain-fndoublequote
    - ENV=plain-fnquote
    - ENV=plain-fntriplequote
    - ENV=plain-pnaccents
    - ENV=plain-pndoublequote
    - ENV=plain-pnquote
    - ENV=plain-pntriplequote
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config user.email "you@example.com"
  - git config user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always

