language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=
    - ENV=cext
    - ENV=cext-optional
    - ENV=fnaccents
    - ENV=fndoublequote
    - ENV=fnquote
    - ENV=fntriplequote
    - ENV=matrix
    - ENV=matrix-cext
    - ENV=matrix-cext-optional
    - ENV=matrix-fnaccents
    - ENV=matrix-fndoublequote
    - ENV=matrix-fnquote
    - ENV=matrix-fntriplequote
    - ENV=matrix-pnaccents
    - ENV=matrix-pndoublequote
    - ENV=matrix-pnquote
    - ENV=matrix-pntriplequote
    - ENV=pnaccents
    - ENV=pndoublequote
    - ENV=pnquote
    - ENV=pntriplequote
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install -I -U tox cookiecutter
script:
  - cp ci/envs/$ENV.json ~/.cookiecutterrc'
  - cat ~/.cookiecutterrc
  - cookiecutter --no-input .
  - |
    cd python-nameless
    git init .
    git config user.email "you@example.com"
    git config user.name "Your Name"    
    git add .
    git commit -m "initial."  
    tox
notifications:
  email:
    on_success: never
    on_failure: always

