build: off
version: '{branch}-{build}'
cache:
  - '%LOCALAPPDATA%\pip\Cache'
matrix:
  fast_finish: true
environment:
  matrix:
    - ENV: mconf-sepcov-nose-pure-argpa-pet-flake8-plain-gith
    - ENV: mconf-sepcov-nose-pure-argpa-pet-flake8-plain-priv
    - ENV: mconf-sepcov-nose-pure-click-pet-flake8-plain-gith
    - ENV: mconf-sepcov-nose-pure-click-pet-flake8-plain-priv
    - ENV: mconf-sepcov-nose-pure-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-nose-pure-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-nose-pure-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-nose-pure-plain-pet-flake8-plain-gith
    - ENV: mconf-sepcov-nose-pure-plain-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cext-nocli-pet-flake8-plain-gith-publish
    - ENV: mconf-sepcov-pyte-cext-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith-publish
    - ENV: mconf-sepcov-pyte-cext-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith-publish
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith-publish
    - ENV: mconf-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cffi-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cffi-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cyth-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-cyth-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-pure-argpa-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-pure-click-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-pure-click-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-pure-nocli-pet-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-pure-nocli-rtd-flake8-plain-priv
    - ENV: mconf-sepcov-pyte-pure-plain-pet-flake8-plain-gith
    - ENV: mconf-sepcov-pyte-pure-plain-pet-flake8-plain-priv
    - ENV: mconf-single-nose-pure-argpa-pet-flake8-plain-gith
    - ENV: mconf-single-nose-pure-argpa-pet-flake8-plain-priv
    - ENV: mconf-single-nose-pure-click-pet-flake8-plain-gith
    - ENV: mconf-single-nose-pure-click-pet-flake8-plain-priv
    - ENV: mconf-single-nose-pure-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-nose-pure-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-nose-pure-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-nose-pure-plain-pet-flake8-plain-gith
    - ENV: mconf-single-nose-pure-plain-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-cext-nocli-pet-flake8-plain-gith-publish
    - ENV: mconf-single-pyte-cext-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-pyte-cext-nocli-rtd-flake8-plain-gith-publish
    - ENV: mconf-single-pyte-cext-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-cext-opt-nocli-pet-flake8-plain-gith-publish
    - ENV: mconf-single-pyte-cext-opt-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith-publish
    - ENV: mconf-single-pyte-cext-opt-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-cffi-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-pyte-cffi-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-cyth-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-pyte-cyth-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-pure-argpa-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-pure-click-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-pure-click-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-pure-nocli-pet-flake8-plain-priv
    - ENV: mconf-single-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV: mconf-single-pyte-pure-nocli-rtd-flake8-plain-priv
    - ENV: mconf-single-pyte-pure-plain-pet-flake8-plain-gith
    - ENV: mconf-single-pyte-pure-plain-pet-flake8-plain-priv
    - ENV: plain-sepcov-nose-pure-argpa-pet-flake8-plain-gith
    - ENV: plain-sepcov-nose-pure-argpa-pet-flake8-plain-priv
    - ENV: plain-sepcov-nose-pure-click-pet-flake8-plain-gith
    - ENV: plain-sepcov-nose-pure-click-pet-flake8-plain-priv
    - ENV: plain-sepcov-nose-pure-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-nose-pure-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-nose-pure-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-nose-pure-plain-pet-flake8-plain-gith
    - ENV: plain-sepcov-nose-pure-plain-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cext-nocli-pet-flake8-plain-gith-publish
    - ENV: plain-sepcov-pyte-cext-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cext-nocli-rtd-flake8-plain-gith-publish
    - ENV: plain-sepcov-pyte-cext-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-gith-publish
    - ENV: plain-sepcov-pyte-cext-opt-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-gith-publish
    - ENV: plain-sepcov-pyte-cext-opt-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cffi-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cffi-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cyth-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-pyte-cyth-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-pure-argpa-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-pure-click-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-pure-click-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-pure-nocli-pet-flake8-plain-priv
    - ENV: plain-sepcov-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV: plain-sepcov-pyte-pure-nocli-rtd-flake8-plain-priv
    - ENV: plain-sepcov-pyte-pure-plain-pet-flake8-plain-gith
    - ENV: plain-sepcov-pyte-pure-plain-pet-flake8-plain-priv
    - ENV: plain-single-nose-pure-argpa-pet-flake8-plain-gith
    - ENV: plain-single-nose-pure-argpa-pet-flake8-plain-priv
    - ENV: plain-single-nose-pure-click-pet-flake8-plain-gith
    - ENV: plain-single-nose-pure-click-pet-flake8-plain-priv
    - ENV: plain-single-nose-pure-nocli-pet-flake8-plain-gith
    - ENV: plain-single-nose-pure-nocli-pet-flake8-plain-priv
    - ENV: plain-single-nose-pure-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-nose-pure-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-nose-pure-plain-pet-flake8-plain-gith
    - ENV: plain-single-nose-pure-plain-pet-flake8-plain-priv
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-plain-gith
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-plain-gith-publish
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-plain-priv
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-stprq-gith-publish
    - ENV: plain-single-pyte-cext-nocli-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-plain-gith
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-plain-gith-publish
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-plain-priv
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-stprq-gith-publish
    - ENV: plain-single-pyte-cext-nocli-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-plain-gith-publish
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-stprq-gith
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-stprq-gith-publish
    - ENV: plain-single-pyte-cext-nocli-rtd-flake8-stprq-priv
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-plain-gith
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-plain-gith-publish
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-plain-priv
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-stprq-gith
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-stprq-gith-publish
    - ENV: plain-single-pyte-cext-nocli-rtd-pylama-stprq-priv
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-plain-gith
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-plain-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-plain-priv
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-stprq-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-plain-gith
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-plain-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-plain-priv
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-stprq-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-plain-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-stprq-gith
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-stprq-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-flake8-stprq-priv
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-plain-gith
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-plain-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-plain-priv
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-stprq-gith
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-stprq-gith-publish
    - ENV: plain-single-pyte-cext-opt-nocli-rtd-pylama-stprq-priv
    - ENV: plain-single-pyte-cffi-nocli-pet-flake8-plain-gith
    - ENV: plain-single-pyte-cffi-nocli-pet-flake8-plain-priv
    - ENV: plain-single-pyte-cffi-nocli-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-cffi-nocli-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-cffi-nocli-pet-pylama-plain-gith
    - ENV: plain-single-pyte-cffi-nocli-pet-pylama-plain-priv
    - ENV: plain-single-pyte-cffi-nocli-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-cffi-nocli-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-cffi-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-pyte-cffi-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-pyte-cffi-nocli-rtd-flake8-stprq-gith
    - ENV: plain-single-pyte-cffi-nocli-rtd-flake8-stprq-priv
    - ENV: plain-single-pyte-cffi-nocli-rtd-pylama-plain-gith
    - ENV: plain-single-pyte-cffi-nocli-rtd-pylama-plain-priv
    - ENV: plain-single-pyte-cffi-nocli-rtd-pylama-stprq-gith
    - ENV: plain-single-pyte-cffi-nocli-rtd-pylama-stprq-priv
    - ENV: plain-single-pyte-cyth-nocli-pet-flake8-plain-gith
    - ENV: plain-single-pyte-cyth-nocli-pet-flake8-plain-priv
    - ENV: plain-single-pyte-cyth-nocli-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-cyth-nocli-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-cyth-nocli-pet-pylama-plain-gith
    - ENV: plain-single-pyte-cyth-nocli-pet-pylama-plain-priv
    - ENV: plain-single-pyte-cyth-nocli-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-cyth-nocli-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-cyth-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-pyte-cyth-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-pyte-cyth-nocli-rtd-flake8-stprq-gith
    - ENV: plain-single-pyte-cyth-nocli-rtd-flake8-stprq-priv
    - ENV: plain-single-pyte-cyth-nocli-rtd-pylama-plain-gith
    - ENV: plain-single-pyte-cyth-nocli-rtd-pylama-plain-priv
    - ENV: plain-single-pyte-cyth-nocli-rtd-pylama-stprq-gith
    - ENV: plain-single-pyte-cyth-nocli-rtd-pylama-stprq-priv
    - ENV: plain-single-pyte-pure-argpa-pet-flake8-plain-gith
    - ENV: plain-single-pyte-pure-argpa-pet-flake8-plain-priv
    - ENV: plain-single-pyte-pure-argpa-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-pure-argpa-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-pure-argpa-pet-pylama-plain-gith
    - ENV: plain-single-pyte-pure-argpa-pet-pylama-plain-priv
    - ENV: plain-single-pyte-pure-argpa-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-pure-argpa-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-pure-click-pet-flake8-plain-gith
    - ENV: plain-single-pyte-pure-click-pet-flake8-plain-priv
    - ENV: plain-single-pyte-pure-click-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-pure-click-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-pure-click-pet-pylama-plain-gith
    - ENV: plain-single-pyte-pure-click-pet-pylama-plain-priv
    - ENV: plain-single-pyte-pure-click-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-pure-click-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-pure-nocli-pet-flake8-plain-gith
    - ENV: plain-single-pyte-pure-nocli-pet-flake8-plain-priv
    - ENV: plain-single-pyte-pure-nocli-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-pure-nocli-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-pure-nocli-pet-pylama-plain-gith
    - ENV: plain-single-pyte-pure-nocli-pet-pylama-plain-priv
    - ENV: plain-single-pyte-pure-nocli-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-pure-nocli-pet-pylama-stprq-priv
    - ENV: plain-single-pyte-pure-nocli-rtd-flake8-plain-gith
    - ENV: plain-single-pyte-pure-nocli-rtd-flake8-plain-priv
    - ENV: plain-single-pyte-pure-nocli-rtd-flake8-stprq-gith
    - ENV: plain-single-pyte-pure-nocli-rtd-flake8-stprq-priv
    - ENV: plain-single-pyte-pure-nocli-rtd-pylama-plain-gith
    - ENV: plain-single-pyte-pure-nocli-rtd-pylama-plain-priv
    - ENV: plain-single-pyte-pure-nocli-rtd-pylama-stprq-gith
    - ENV: plain-single-pyte-pure-nocli-rtd-pylama-stprq-priv
    - ENV: plain-single-pyte-pure-plain-pet-flake8-plain-gith
    - ENV: plain-single-pyte-pure-plain-pet-flake8-plain-priv
    - ENV: plain-single-pyte-pure-plain-pet-flake8-stprq-gith
    - ENV: plain-single-pyte-pure-plain-pet-flake8-stprq-priv
    - ENV: plain-single-pyte-pure-plain-pet-pylama-plain-gith
    - ENV: plain-single-pyte-pure-plain-pet-pylama-plain-priv
    - ENV: plain-single-pyte-pure-plain-pet-pylama-stprq-gith
    - ENV: plain-single-pyte-pure-plain-pet-pylama-stprq-priv
init:
  - "echo %CTX%"
  - "set"
  - ps: "ls C:\\Python*"
install:
  - ps: if (Test-Path c:/Users/appveyor/pip/wheels) { ls c:/Users/appveyor/pip/wheels } else { echo Wheelhouse missing. }
  - ps: New-Item -Force -ItemType directory -Path "c:/Users/appveyor/pip/wheels"
  - ps: ls c:/Users/appveyor/pip/wheels
  - ps: Copy-Item -Path "./ci/pip.ini" -Destination "c:/Users/appveyor/pip/pip.ini" -Force
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\get-pip.py setuptools"
  - "c:\\python27\\Scripts\\pip wheel tox virtualenv cookiecutter bumpversion"
  - "c:\\python27\\Scripts\\pip wheel pytest-capturelog pytest-cov pytest"
  - "c:\\python27\\Scripts\\pip wheel nose coverage"
  - "c:\\python27\\Scripts\\pip wheel cpp-coveralls"
  - "c:\\python27\\Scripts\\pip wheel jinja2 matrix"
  - "c:\\python27\\Scripts\\pip wheel docutils check-manifest flake8 readme-renderer pygments"
  - "c:\\python27\\Scripts\\pip install --upgrade tox virtualenv cookiecutter"
test_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - powershell ci\\test.ps1 $Env:ENV
