build: false
environment:
  matrix:
    - ENV: 
    - ENV: cext
    - ENV: cext-optional
    - ENV: fnaccents
    - ENV: fndoublequote
    - ENV: fnquote
    - ENV: fntriplequote
    - ENV: matrix
    - ENV: matrix-cext
    - ENV: matrix-cext-optional
    - ENV: matrix-fnaccents
    - ENV: matrix-fndoublequote
    - ENV: matrix-fnquote
    - ENV: matrix-fntriplequote
    - ENV: matrix-pnaccents
    - ENV: matrix-pndoublequote
    - ENV: matrix-pnquote
    - ENV: matrix-pntriplequote
    - ENV: pnaccents
    - ENV: pndoublequote
    - ENV: pnquote
    - ENV: pntriplequote
init:
  - "echo %CTX%"
  - "set"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install -I -U tox virtualenv cookiecutter"
test_script:
  - ps: cat "ci/envs/$Env:ENV.json" | Set-Content -Path ("{0}{1}\\.cookiecutterrc" -f $Env:HOMEDRIVE,$Env:HOMEPATH)
  - "c:\\python27\\Scripts\\cookiecutter --no-input ."
  - |
    cd python-nameless
    git init .
    git config user.email "you@example.com"
    git config user.name "Your Name"    
    git add .
    git commit -m "initial."  
    c:\\python27\\Scripts\\tox --skip-missing-interpreters
