build: false
environment:
  matrix:
    - ENV: matrix
    - ENV: matrix-cext
    - ENV: matrix-cext-optional
    - ENV: matrix-fnaccents
    - ENV: matrix-fndoublequote
    - ENV: matrix-fnquote
    - ENV: matrix-fntriplequote
    - ENV: matrix-pnaccents
    - ENV: matrix-pndoublequote
    - ENV: matrix-pnquote
    - ENV: matrix-pntriplequote
    - ENV: plain
    - ENV: plain-cext
    - ENV: plain-cext-optional
    - ENV: plain-fnaccents
    - ENV: plain-fndoublequote
    - ENV: plain-fnquote
    - ENV: plain-fntriplequote
    - ENV: plain-pnaccents
    - ENV: plain-pndoublequote
    - ENV: plain-pnquote
    - ENV: plain-pntriplequote
init:
  - "echo %CTX%"
  - "set"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install -I -U tox virtualenv cookiecutter"
test_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - powershell ci\\test.ps1 $Env:ENV
