build: false
environment:
  matrix:
{% for env, config in tox_environments|dictsort %}
    - ENV: {{ env }}
{% endfor %}
init:
  - "echo %CTX%"
  - "set"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install -I -U tox virtualenv cookiecutter"
test_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - powershell ci\\test.ps1 $Env:ENV
